/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <UART_BOOT.h>
#include <CapSense_CSD.h>
#include <CapSense_CSD_CSHL.h>
#include <CapSense_CSD_TunerHelper.h>
#include <CapSense_CSD_PVT.h>
#include <CapSense_CSD_IP.h>
#include <Pin_GreenLED.h>
#include <Pin_GreenLED_aliases.h>
#include <counter_isr.h>
#include <Counter_Controll_Register.h>
#include <Pin_BlueLED.h>
#include <Pin_BlueLED_aliases.h>
#include <Clock.h>
#include <PWM.h>
#include <Clock_PWM.h>
#include <Pin_RedLED.h>
#include <Pin_RedLED_aliases.h>
#include <PWM_R.h>
#include <PWM_G.h>
#include <PWM_B.h>
#include <UART_SCBCLK.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <CapSense_CSD_SampleClk.h>
#include <CapSense_CSD_Sns.h>
#include <CapSense_CSD_Sns_aliases.h>
#include <CapSense_CSD_SenseClk.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

